import type { CountryCode } from "./country-config";

export type CountryLocationDirectory = {
  divisionLabel: string;
  divisionPlural: string;
  cityLabel: string;
  divisions: Record<string, string[]>;
};

export const countryLocationDirectories: Record<CountryCode, CountryLocationDirectory> = {
  ae: {
    divisionLabel: "Emirate",
    divisionPlural: "Emirates",
    cityLabel: "City / area",
    divisions: {
      Dubai: ["Dubai", "Deira", "Jebel Ali", "Hatta"],
      "Abu Dhabi": ["Abu Dhabi", "Al Ain", "Madinat Zayed", "Ruwais"],
      Sharjah: ["Sharjah", "Khor Fakkan", "Kalba", "Dibba Al-Hisn"],
      Ajman: ["Ajman", "Masfout", "Manama"],
      "Ras Al Khaimah": ["Ras Al Khaimah", "Al Jazirah Al Hamra", "Rams"],
      Fujairah: ["Fujairah", "Dibba Al-Fujairah", "Al Bidyah"],
      "Umm Al Quwain": ["Umm Al Quwain", "Falaj Al Mualla"],
    },
  },
  in: {
    divisionLabel: "State / Union Territory",
    divisionPlural: "States and Union Territories",
    cityLabel: "City",
    divisions: {
      "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Nellore"],
      "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang"],
      Assam: ["Guwahati", "Dibrugarh", "Silchar", "Jorhat", "Tezpur"],
      Bihar: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"],
      Chhattisgarh: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
      Goa: ["Panaji", "Margao", "Vasco da Gama", "Mapusa"],
      Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
      Haryana: ["Gurugram", "Faridabad", "Panipat", "Ambala", "Hisar"],
      "Himachal Pradesh": ["Shimla", "Dharamshala", "Solan", "Mandi", "Kullu"],
      Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar"],
      Karnataka: ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"],
      Kerala: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur"],
      "Madhya Pradesh": ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"],
      Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad"],
      Manipur: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
      Meghalaya: ["Shillong", "Tura", "Jowai", "Nongpoh"],
      Mizoram: ["Aizawl", "Lunglei", "Champhai", "Kolasib"],
      Nagaland: ["Kohima", "Dimapur", "Mokokchung", "Wokha"],
      Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Sambalpur"],
      Punjab: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Mohali"],
      Rajasthan: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner"],
      Sikkim: ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
      "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tiruppur"],
      Telangana: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"],
      Tripura: ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar"],
      "Uttar Pradesh": ["Lucknow", "Kanpur", "Noida", "Ghaziabad", "Agra", "Varanasi", "Prayagraj"],
      Uttarakhand: ["Dehradun", "Haridwar", "Haldwani", "Roorkee", "Rishikesh"],
      "West Bengal": ["Kolkata", "Howrah", "Siliguri", "Durgapur", "Asansol"],
      "Andaman and Nicobar Islands": ["Port Blair", "Diglipur", "Mayabunder"],
      Chandigarh: ["Chandigarh"],
      "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
      Delhi: ["New Delhi", "Delhi", "Dwarka", "Rohini", "Saket"],
      "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla"],
      Ladakh: ["Leh", "Kargil"],
      Lakshadweep: ["Kavaratti", "Agatti", "Minicoy"],
      Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
    },
  },
  uk: {
    divisionLabel: "Constituent country",
    divisionPlural: "Constituent countries",
    cityLabel: "City / town",
    divisions: {
      England: ["London", "Birmingham", "Manchester", "Liverpool", "Leeds", "Bristol", "Newcastle", "Sheffield", "Nottingham"],
      Scotland: ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness", "Stirling"],
      Wales: ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor"],
      "Northern Ireland": ["Belfast", "Derry/Londonderry", "Lisburn", "Newry", "Armagh"],
    },
  },
  us: {
    divisionLabel: "State",
    divisionPlural: "States",
    cityLabel: "City",
    divisions: {
      Alabama: ["Birmingham", "Montgomery", "Mobile", "Huntsville"], Alaska: ["Anchorage", "Fairbanks", "Juneau"],
      Arizona: ["Phoenix", "Tucson", "Mesa", "Scottsdale"], Arkansas: ["Little Rock", "Fayetteville", "Fort Smith"],
      California: ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "San Jose"], Colorado: ["Denver", "Colorado Springs", "Aurora", "Boulder"],
      Connecticut: ["Bridgeport", "New Haven", "Stamford", "Hartford"], Delaware: ["Wilmington", "Dover", "Newark"],
      Florida: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"], Georgia: ["Atlanta", "Savannah", "Augusta", "Columbus"],
      Hawaii: ["Honolulu", "Hilo", "Kailua", "Kahului"], Idaho: ["Boise", "Meridian", "Nampa", "Idaho Falls"],
      Illinois: ["Chicago", "Springfield", "Aurora", "Rockford"], Indiana: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"],
      Iowa: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"], Kansas: ["Wichita", "Overland Park", "Kansas City", "Topeka"],
      Kentucky: ["Louisville", "Lexington", "Bowling Green", "Owensboro"], Louisiana: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
      Maine: ["Portland", "Lewiston", "Bangor", "Augusta"], Maryland: ["Baltimore", "Frederick", "Rockville", "Annapolis"],
      Massachusetts: ["Boston", "Worcester", "Springfield", "Cambridge"], Michigan: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"],
      Minnesota: ["Minneapolis", "Saint Paul", "Rochester", "Duluth"], Mississippi: ["Jackson", "Gulfport", "Southaven", "Biloxi"],
      Missouri: ["Kansas City", "St. Louis", "Springfield", "Columbia"], Montana: ["Billings", "Missoula", "Great Falls", "Bozeman"],
      Nebraska: ["Omaha", "Lincoln", "Bellevue", "Grand Island"], Nevada: ["Las Vegas", "Reno", "Henderson", "Carson City"],
      "New Hampshire": ["Manchester", "Nashua", "Concord", "Portsmouth"], "New Jersey": ["Newark", "Jersey City", "Paterson", "Trenton"],
      "New Mexico": ["Albuquerque", "Las Cruces", "Santa Fe", "Rio Rancho"], "New York": ["New York City", "Buffalo", "Rochester", "Albany"],
      "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham"], "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot"],
      Ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo"], Oklahoma: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
      Oregon: ["Portland", "Eugene", "Salem", "Bend"], Pennsylvania: ["Philadelphia", "Pittsburgh", "Allentown", "Harrisburg"],
      "Rhode Island": ["Providence", "Warwick", "Cranston", "Newport"], "South Carolina": ["Charleston", "Columbia", "Greenville", "Myrtle Beach"],
      "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"], Tennessee: ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
      Texas: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"], Utah: ["Salt Lake City", "Provo", "Ogden", "St. George"],
      Vermont: ["Burlington", "South Burlington", "Rutland", "Montpelier"], Virginia: ["Virginia Beach", "Richmond", "Norfolk", "Arlington"],
      Washington: ["Seattle", "Spokane", "Tacoma", "Bellevue"], "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg"],
      Wisconsin: ["Milwaukee", "Madison", "Green Bay", "Kenosha"], Wyoming: ["Cheyenne", "Casper", "Laramie", "Gillette"],
      "District of Columbia": ["Washington"],
    },
  },
};
